app:
  ~chart: app
  ~needs: [pg]
  probesPath: /api/healthz
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: proconnect
    - configMapRef:
        name: da-manager
  env:
    - name: PROCONNECT_ISSUER
      value: "https://fca.integ01.dev-agentconnect.fr/api/v2"

pg:
  ~chart: pg
